name: "Release Pipeline"

on:
  push:
    branches:
      - develop
      - main
      - hotfix/*
    paths-ignore:
      - '.gitignore'
      - '**/*.env'   # Ignores all .env files
      - '*.env'      # Ignores .env files in the root directory
      - '**/*.md'    # Ignores all .md files
      - '*.md'       # Ignores .md files in the root directory
      - '**/*.txt'   # Ignores all .env files
      - '*.txt'      # Ignores .env files in the root directory
    tags-ignore: ['**']

permissions:
  id-token: write       # Needed for authentication
  contents: write       # Needed to create releases and tags
  pull-requests: write  # Needed to create/update PRs
  packages: read        # Needed to publish packages

jobs:
  # Publish release using the lerian-studio/github-actions-go-pipeline-template
  publish-release:
    uses: LerianStudio/github-actions-go-pipeline-template/.github/workflows/release.yml@develop
    secrets:
      lerian_studio_push_bot_app_id: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
      lerian_studio_push_bot_private_key: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}
      lerian_ci_cd_user_gpg_key: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY }}
      lerian_ci_cd_user_gpg_key_password: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
      lerian_ci_cd_user_name: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
      lerian_ci_cd_user_email: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
      gh_pat_for_packages: ${{ secrets.GH_PAT_FOR_PACKAGES }}